export const GET_TRUCK_TYPES = 'GET_TRUCK_TYPES';
export const GET_SHIPMENT_BY_DRIVER = 'GET_SHIPMENT_BY_DRIVER';
export const AUTO_SUGGEST_PLACES = 'AUTO_SUGGEST_PLACES';
export const DRIVER_SHIPMENT_LOG = 'DRIVER_SHIPMENT_LOG';
